/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely';

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export interface Messages {
  created_at_epoch_ms: Generated<Int8>;
  destination_run_id: string;
  id: Generated<string>;
  payload: string | null;
  type: string | null;
}

export interface Operations {
  child_run_id: string | null;
  completed_at_epoch_ms: Int8 | null;
  error: string | null;
  name: string;
  output: string | null;
  run_id: string;
  sequence_id: number;
  started_at_epoch_ms: Int8 | null;
}

export interface Runs {
  change_id: Generated<number>;
  created_at: Generated<Int8>;
  deadline_epoch_ms: Int8 | null;
  error: string | null;
  executor_id: string | null;
  forked_from_run_id: string | null;
  id: Generated<string>;
  idempotency_key: string | null;
  inputs: string | null;
  output: string | null;
  parent_run_id: string | null;
  path: string[];
  queue_deduplication_id: string | null;
  queue_name: string | null;
  queue_partition_key: string | null;
  recovery_attempts: Generated<Int8>;
  status: string;
  timeout_ms: Int8 | null;
  updated_at: Generated<Int8>;
  workflow_name: string;
}

export interface State {
  change_id: Generated<number>;
  key: string;
  run_id: string;
  value: string;
}

export interface StateHistory {
  change_id: Generated<number>;
  key: string;
  run_id: string;
  sequence_id: number;
  value: string;
}

export interface DB {
  messages: Messages;
  operations: Operations;
  runs: Runs;
  state: State;
  state_history: StateHistory;
}
